create table
  public."AcademicYear" (
    id bigint generated by default as identity not null,
    starting_year integer not null,
    ending_year integer not null,
    constraint Settings_pkey primary key (id)
  ) tablespace pg_default;