create table
  public."AIMessages" (
    chat_message_id bigint generated by default as identity not null,
    sender_id uuid null,
    receiver_id uuid null,
    message text not null,
    created_at timestamp with time zone not null default now(),
    constraint aichatmessages_pkey primary key (chat_message_id),
    constraint aichatmessages_sender_id_fkey foreign key (sender_id) references auth.users (id) on update cascade on delete cascade,
    constraint aichatmessages_receiver_id_fkey foreign key (receiver_id) references auth.users (id) on update cascade on delete cascade
  ) tablespace pg_default;