create table
  "BiddingTransactions" (
    bid_id bigint generated by default as identity not null,
    item_id bigint not null,
    bidder_id uuid not null,
    bid_price bigint not null,
    bid_due timestamp without time zone not null,
    bid_status character varying not null default 'active'::character varying,
    created_at timestamp with time zone not null default now(),
    constraint biddingtransactions_pkey primary key (bid_id),
    constraint biddingtransactions_bidder_id_fkey foreign key (bidder_id) references auth.users (id) on update cascade on delete cascade,
    constraint biddingtransactions_item_id_fkey foreign key (item_id) references "ItemInventory" (item_id) on update cascade on delete cascade
  ) tablespace pg_default;