create table
  "ChatMessages" (
    chat_message_id bigint generated by default as identity not null,
    sender_id uuid not null,
    receiver_id uuid not null,
    message text not null,
    last_accessed_at timestamp with time zone not null default now(),
    created_at timestamp with time zone not null default now(),
    constraint ChatMessages_pkey primary key (chat_message_id),
    constraint ChatMessages_receiver_id_fkey foreign key (receiver_id) references auth.users (id) on update cascade on delete cascade,
    constraint ChatMessages_sender_id_fkey foreign key (sender_id) references auth.users (id) on update cascade on delete cascade
  ) tablespace pg_default;