create table
  "ItemInventory" (
    item_id bigint generated by default as identity not null,
    seller_id uuid not null,
    item_name character varying not null,
    item_price double precision not null,
    item_category character varying not null, -- 'fashion', 'electronics', 'home', 'beauty', 'toys', 'books', 'sports', 'others'
    item_condition character varying not null,
    item_description text null,
    item_status text not null default 'pending'::text, -- 'pending', 'active', 'sold'
    item_selling_type text not null, -- 'auction', 'buy_now'
    image_urls jsonb not null,
    created_at timestamp with time zone not null default now(),
    constraint iteminventory_pkey primary key (item_id),
    constraint iteminventory_seller_id_fkey foreign key (seller_id) references auth.users (id) on update cascade on delete cascade
  ) tablespace pg_default;