create table
  public."Users" (
    user_id bigint generated by default as identity not null,
    auth_user_id uuid null,
    first_name text not null,
    last_name text not null,
    role text not null,
    email text not null,
    password text not null,
    created_at timestamp with time zone not null default now(),
    status text not null default 'pending'::text,
    year_level smallint not null,
    school_id_number text not null,
    constraint Users_pkey primary key (user_id),
    constraint Users_email_key unique (email),
    constraint Users_auth_user_id_fkey foreign key (auth_user_id) references auth.users (id) on update cascade on delete cascade
  ) tablespace pg_default;