export const sellMockupData = [
  {
    id: 2,
    imageUrl: "https://nextui.org/images/album-cover.png",
    productName: "Product Name 2",
    productPrice: "PHP 1,000",
    tag: "Electronics",
    sellerAvatar: "https://i.pravatar.cc/150?u=a042581f4e29026789d",
    sellerName: "Seller Name 2",
  },
  {
    id: 1,
    imageUrl: "https://nextui.org/images/hero-card-complete.jpeg",
    productName: "Product Name 1",
    productPrice: "PHP 400",
    tag: "Clothing",
    sellerAvatar: "https://i.pravatar.cc/150?u=a042581f4e29026024d",
    sellerName: "Seller Name 1",
  },

  {
    id: 3,
    imageUrl: "https://nextui.org/images/hero-card-complete.jpeg",
    productName: "Product Name 1",
    productPrice: "PHP 400",
    tag: "Furniture",
    sellerAvatar: "https://i.pravatar.cc/150?u=a042581f4e29026024d",
    sellerName: "Seller Name 1",
  },
  {
    id: 4,
    imageUrl: "https://nextui.org/images/album-cover.png",
    productName: "Product Name 2",
    productPrice: "PHP 1,000",
    tag: "Footwear",
    sellerAvatar: "https://i.pravatar.cc/150?u=a042581f4e29026789d",
    sellerName: "Seller Name 2",
  },
  {
    id: 5,
    imageUrl: "https://nextui.org/images/hero-card-complete.jpeg",
    productName: "Product Name 1",
    productPrice: "PHP 400",
    tag: "Accessories",
    sellerAvatar: "https://i.pravatar.cc/150?u=a042581f4e29026024d",
    sellerName: "Seller Name 1",
  },
  {
    id: 6,
    imageUrl: "https://nextui.org/images/album-cover.png",
    productName: "Product Name 2",
    productPrice: "PHP 1,000",
    tag: "Bag",
    sellerAvatar: "https://i.pravatar.cc/150?u=a042581f4e29026789d",
    sellerName: "Seller Name 2",
  },
  {
    id: 7,
    imageUrl: "https://nextui.org/images/hero-card-complete.jpeg",
    productName: "Product Name 1",
    productPrice: "PHP 400",
    tag: "Clothing",
    sellerAvatar: "https://i.pravatar.cc/150?u=a042581f4e29026024d",
    sellerName: "Seller Name 1",
  },
  {
    id: 8,
    imageUrl: "https://nextui.org/images/album-cover.png",
    productName: "Product Name 2",
    productPrice: "PHP 1,000",
    tag: "Electronics",
    sellerAvatar: "https://i.pravatar.cc/150?u=a042581f4e29026789d",
    sellerName: "Seller Name 2",
  },
];
