create table
  public."BiddingTransactions" (
    id bigint generated by default as identity not null,
    item_list_id bigint not null,
    bidder_id uuid not null,
    bid_price bigint not null,
    bid_due timestamp without time zone not null,
    status character varying not null default 'active'::character varying,
    created_at timestamp with time zone not null default now(),
    constraint BiddingTransactions_pkey primary key (id),
    constraint BiddingTransactions_bidder_id_fkey foreign key (bidder_id) references auth.users (id) on update cascade on delete cascade,
    constraint BiddingTransactions_item_list_id_fkey foreign key (item_list_id) references "ItemInventory" (id) on update cascade on delete cascade
  ) tablespace pg_default;