create table
  public."ItemInventory" (
    id bigint generated by default as identity not null,
    seller_id uuid not null,
    item_name character varying not null,
    item_price double precision not null,
    item_category character varying not null,
    item_condition character varying not null,
    created_at timestamp with time zone not null default now(),
    constraint ItemInventory_pkey primary key (id),
    constraint ItemInventory_seller_id_fkey foreign key (seller_id) references auth.users (id) on update cascade on delete cascade
  ) tablespace pg_default;