create table
  public."SoldItemsInventory" (
    sold_item_id bigint generated by default as identity not null,
    item_list_id bigint null,
    buyer_id uuid null,
    bid_price double precision null,
    created_at timestamp with time zone not null default now(),
    constraint solditemsinventory_pkey primary key (sold_item_id),
    constraint solditemsinventory_buyer_id_fkey foreign key (buyer_id) references auth.users (id) on update cascade on delete cascade,
    constraint solditemsinventory_item_list_id_fkey foreign key (item_list_id) references "ItemInventory" (item_id) on update cascade on delete cascade
  ) tablespace pg_default;