create table
  public."Users" (
    id bigint generated by default as identity not null,
    user_id text null,
    first_name text not null,
    last_name text not null,
    role text not null,
    year_level smallint not null,
    school_id_number text not null,
    email text not null,
    password text not null,
    status text not null default 'pending'::text,
    created_at timestamp with time zone not null default now(),
    constraint Users_pkey primary key (id)
    constraint Users_email_key unique (email)
  ) tablespace pg_default;